# Gradle Specifications
org.gradle.jvmargs=-Xms256M -Xmx2G
org.gradle.daemon=false

# General Specifications
mc_version=1.12.2
mod_version=1.1.6-BETA
forge_version=14.23.5.2855
mod_group=aromara
mod_id=aromara
mod_name=Aromara Thaumcraft
mod_archives_name=AromaraThaumcraft
mod_author=leonidleskovetz
mod_icon=TEM_logo.png
mod_description=Aromara is a small Thaumcraft addon adding various interactions with smells & aromas
mod_credits=