package aromara.util;

public class Researches {

    public static String CAT_TCA = "SCENTMIXING";

    public static String CAT_ALCHEMY = "ALCHEMY";
    public static String CAT_ARTIFICE = "ARTIFICE";
    public static String CAT_AUROMANCY = "AUROMANCY";
    public static String CAT_BASICS = "BASICS";
    public static String CAT_ELDRITCH = "ELDRITCH";
    public static String CAT_GOLEMANCY = "GOLEMANCY";
    public static String CAT_INFUSTION = "INFUSION";


    public enum TCAkey{
        BASESCENTMIXING("BASESCENTMIXING"),

        DISTURBINGTHOUGHTS("DISTURBINGTHOUGHTS"),
        SPORETHEORY("SPORETHEORY"),
        TAINTPARASITES("TAINTPARASITES");

        private final String value;

        TCAkey(String value) {
            this.value = value;
        }

        public String get() {
            return "TCA:" + this.value;
        }
    }

    public enum TCkey {
        UNLOCKARTIFICE("UNLOCKARTIFICE"),
        ORE("ORE"),
        FLUX("FLUX"),
        UNLOCKAUROMANCY("UNLOCKAUROMANCY"),
        WISP("!Wisp"),
        CRYSTALFARMER("CRYSTALFARMER"),
        UNLOCKALCHEMY("UNLOCKALCHEMY"),
        CRIMSONCULTIST("!CrimsonCultist"),
        ELDRITCHCRAB("!EldritchCrab"),
        PRIMPEARL("PRIMPEARL"),
        UNLOCKELDRITCH("UNLOCKELDRITCH"),
        FLUXRIFT("FLUXRIFT"),
        FIRSTSTEPS("FIRSTSTEPS"),
        KNOWLEDGETYPES("KNOWLEDGETYPES"),
        UNLOCKGOLEMANCY("UNLOCKGOLEMANCY"),
        WARP("WARP"),
        THEORYRESEARCH("THEORYRESEARCH"),
        FIREBAT("!Firebat"),
        UNLOCKINFUSION("UNLOCKINFUSION"),
        CELESTIALSCANNING("CELESTIALSCANNING"),
        FLUXCLEANUP("FLUXCLEANUP"),
        ELDRITCHGUARDIAN("!EldritchGuardian"),
        PECH("!Pech"),
        TAINTACLE("!Taintacle"),
        TAINTCRAWLER("!TaintCrawler"),
        BRAINYZOMBIE("!BrainyZombie"),
        RIFTCLOSER("RIFTCLOSER"),
        CRIMSONRITES("CrimsonRites"),
        TAINTSWARM("!TaintSwarm"),
        THAUMSLIME("!ThaumSlime"),
        PLANTS("PLANTS"),
        TAINTSEED("!TaintSeed"),
        FOCUSPOUCH("FOCUSPOUCH"),
        WORKBENCHCHARGER("WORKBENCHCHARGER"),
        FOCUSRIFT("FOCUSRIFT"),
        FOCUSSCATTER("FOCUSSCATTER"),
        FOCUSEXCHANGE("FOCUSEXCHANGE"),
        FOCUSGREATER("FOCUSGREATER"),
        FOCUSSPLIT("FOCUSSPLIT"),
        BASEAUROMANCY("BASEAUROMANCY"),
        FOCUSELEMENTAL("FOCUSELEMENTAL"),
        FOCUSFLUX("FOCUSFLUX"),
        VISBATTERY("VISBATTERY"),
        FOCUSHEAL("FOCUSHEAL"),
        FOCUSCLOUD("FOCUSCLOUD"),
        FOCUSPLAN("FOCUSPLAN"),
        FOCUSCURSE("FOCUSCURSE"),
        FOCUSBREAK("FOCUSBREAK"),
        FOCUSADVANCED("FOCUSADVANCED"),
        FOCUSPROJECTILE("FOCUSPROJECTILE"),
        VISAMULET("VISAMULET"),
        FOCUSBOLT("FOCUSBOLT"),
        FOCUSMINE("FOCUSMINE"),
        FOCUSSPELLBAT("FOCUSSPELLBAT"),
        RECHARGEPEDESTAL("RECHARGEPEDESTAL"),
        ALUMENTUM("ALUMENTUM"),
        POTIONSPRAYER("POTIONSPRAYER"),
        HEDGEALCHEMY("HEDGEALCHEMY"),
        BATHSALTS("BATHSALTS"),
        BASEALCHEMY("BASEALCHEMY"),
        ESSENTIASMELTERTHAUMIUM("ESSENTIASMELTERTHAUMIUM"),
        ESSENTIASMELTERVOID("ESSENTIASMELTERVOID"),
        ARCANESPA("ARCANESPA"),
        THAUMATORIUM("THAUMATORIUM"),
        ESSENTIATRANSPORT("ESSENTIATRANSPORT"),
        LIQUIDDEATH("LIQUIDDEATH"),
        TUBES("TUBES"),
        IMPROVEDSMELTING("IMPROVEDSMELTING"),
        CENTRIFUGE("CENTRIFUGE"),
        WARDEDJARS("WARDEDJARS"),
        IMPROVEDSMELTING2("IMPROVEDSMELTING2"),
        BOTTLETAINT("BOTTLETAINT"),
        EVERFULLURN("EVERFULLURN"),
        METALLURGY("METALLURGY"),
        SANESOAP("SANESOAP"),
        ESSENTIASMELTER("ESSENTIASMELTER"),
        METALPURIFICATION("METALPURIFICATION"),
        MIRRORHAND("MIRRORHAND"),
        ARCANELAMP("ARCANELAMP"),
        VISINATOR("visinator"),
        BELLOWS("BELLOWS"),
        MIRRORESSENTIA("MIRRORESSENTIA"),
        DIOPTRA("DIOPTRA"),
        HUNGRYCHEST("HUNGRYCHEST"),
        ARCANEEAR("ARCANEEAR"),
        GRAPPLEGUN("GRAPPLEGUN"),
        ARCANEPATTERNCRAFTER("ARCANEPATTERNCRAFTER"),
        MIRROR("MIRROR"),
        INFERNALFURNACE("INFERNALFURNACE"),
        BASICTURRET("BASICTURRET"),
        LAMPFERTILITY("LAMPFERTILITY"),
        LEVITATOR("LEVITATOR"),
        LAMPGROWTH("LAMPGROWTH"),
        VISGENERATOR("VISGENERATOR"),
        ADVANCEDTURRET("ADVANCEDTURRET"),
        BASEARTIFICE("BASEARTIFICE"),
        ARCANEBORE("ARCANEBORE"),
        REDSTONERELAY("REDSTONERELAY"),
        RUNICSHIELDING("RUNICSHIELDING"),
        INFUSIONBOOST("INFUSIONBOOST"),
        ARMORFORTRESS("ARMORFORTRESS"),
        INFUSIONSTABLE("INFUSIONSTABLE"),
        INFUSIONELDRITCH("INFUSIONELDRITCH"),
        INFUSIONANCIENT("INFUSIONANCIENT"),
        INFUSION("INFUSION"),
        PAVINGSTONES("PAVINGSTONES"),
        CURIOSITYBAND("CURIOSITYBAND"),
        FORTRESSMASK("FORTRESSMASK"),
        CHARMUNDYING("CHARMUNDYING"),
        VERDANTCHARMS("VERDANTCHARMS"),
        BASEINFUSION("BASEINFUSION"),
        CLOUDRING("CLOUDRING"),
        BOOTSTRAVELLER("BOOTSTRAVELLER"),
        ELEMENTALTOOLS("ELEMENTALTOOLS"),
        INFUSIONENCHANTMENT("INFUSIONENCHANTMENT"),
        BASEGOLEMANCY("BASEGOLEMANCY"),
        SEALLUMBER("SEALLUMBER"),
        MINDCLOCKWORK("MINDCLOCKWORK"),
        GOLEMBREAKER("GOLEMBREAKER"),
        SEALBUTCHER("SEALBUTCHER"),
        MATSTUDCLAY("MATSTUDCLAY"),
        SEALBREAK("SEALBREAK"),
        MATSTUDBRASS("MATSTUDBRASS"),
        SEALUSE("SEALUSE"),
        GOLEMCLIMBER("GOLEMCLIMBER"),
        SEALSTORE("SEALSTORE"),
        SEALCOLLECT("SEALCOLLECT"),
        MATSTUDIRON("MATSTUDIRON"),
        SEALEMPTY("SEALEMPTY"),
        SEALSTOCK("SEALSTOCK"),
        MATSTUDVOID("MATSTUDVOID"),
        SEALPROVIDE("SEALPROVIDE"),
        MATSTUDTHAUMIUM("MATSTUDTHAUMIUM"),
        CONTROLSEALS("CONTROLSEALS"),
        SEALHARVEST("SEALHARVEST"),
        MINDBIOTHAUMIC("MINDBIOTHAUMIC"),
        GOLEMVISION("GOLEMVISION"),
        GOLEMFLYER("GOLEMFLYER"),
        GOLEMDIRECT("GOLEMDIRECT"),
        GOLEMCOMBATADV("GOLEMCOMBATADV"),
        JARBRAIN("JARBRAIN"),
        GOLEMLOGISTICS("GOLEMLOGISTICS"),
        MATSTUDWOOD("MATSTUDWOOD"),
        SEALGUARD("SEALGUARD"),
        VOIDSEERPEARL("VOIDSEERPEARL"),
        VOIDROBEARMOR("VOIDROBEARMOR"),
        PRIMALCRUSHER("PRIMALCRUSHER"),
        VOIDSIPHON("VOIDSIPHON"),
        BASEELDRITCH("BASEELDRITCH"),
        FAKEFLUXRIFT("FAKEFLUXRIFT"),
        FAKE_TAINTSEED("!FakeTaintSeed"),
        FAKEBASEELDRITCH("FAKEBASEELDRITCH"),
        WARFARE("WARFARE");

        private final String value;

        TCkey(String value) {
            this.value = value;
        }

        public String get() {
            return this.value;
        }
    }

}